version: '3'

services:
  app-dev:
    container_name: ac-multiposter-dev
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - 5173:5173
    restart: unless-stopped
    command: sh -c "/app/docker/startup-dev.sh"

  db-dev:
    container_name: ac-multiposter-dev-psql
    image: postgres:15.15-alpine
    environment:
      - POSTGRES_USER=ac-multiposter
      - POSTGRES_PASSWORD=ac-multiposter
    volumes:
      - ac-multiposter-dev-psql:/var/lib/postgresql/data
    restart: unless-stopped

  db-dev-admin:
    container_name: ac-multiposter-dev-pgadmin
    image: dpage/pgadmin4:9.10
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@foo.bar
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - db-dev

volumes:
  ac-multiposter-dev-psql: